### PR TITLE
Add clients ML support (close #2)

### LINKED ISSUE #2: [feature] Add multilang support
Need to add clients (not server) multilang support.

### PR DESCRIPTION
**Pull request by wopox1337**
Close #2

### CODE REVIEW

**Comment by SmileYzn** [comment]
I used only the server language configuration, since main idea is configure language in whole server.
And the mod do not need an client configuration menu for language like in amxx do.

**Comment by SmileYzn** [comment]
Closed duo new version

**Comment by wopox1337** [comment]
> I used only the server language configuration, since main idea is configure language in whole server. And the mod do not need an client configuration menu for language like in amxx do.

AMXX has a setting for this behavior:
https://github.com/alliedmodders/amxmodx/blob/master/configs/amxx.cfg#L143-L147

**Comment by SmileYzn** [comment]
You need manually input the amxmodx plugin to reach this, with amxx lang menu.  
Maybe create a new plugin to do this..  


Only server language can be changed in pug using amxx.cfg.

**Pull request closed without merging**
