### PR TITLE
Add 'Stay Here' option in vote map

### PR DESCRIPTION
**Pull request by DionnyV**
When the server is empty and people start connecting they would like to play the map that the server is on.

### CODE REVIEW

**Comment by SmileYzn** [comment]
Nice, but i need to review these changes, it think only remove the check if is same map and adjust menu load will work.

Ps.
Anyway i think if players already played in current map, and vote starts why is supposed to play the same map again?
You can explain this?  So maybe i can do a better menu for pug.

Thanks

**Comment by DionnyV** [comment]
> Nice, but i need to review these changes, it think only remove the check if is same map and adjust menu load will work.
> 
> Ps.
> Anyway i think if players already played in current map, and vote starts why is supposed to play the same map again?
> You can explain this? So maybe i can do a better menu for pug.
> 
> Thanks

Let's suppose 10 people finish playing the map and disconnect from the server, the same map that they just played remains (for example: de_dust2), 10 other different people connect and they want to play de_dust2. The mod doesn't give them the option to play de_dust2 (or stay here) because a game has already ended on that map. Another reason is that if the server has just turned on, the vote map will come out but you will not be able to play the map that you have set as default (+map).

**Comment by SmileYzn** [comment]
If you started server, there is no vote in first pug session, since pug_vote_map is 0 at .sma file.

https://github.com/SmileYzn/PugMod/blob/d6744365be96c3802aa347945ada93e64e0a6559/addons/amxmodx/scripting/PugMenus.sma#L39

 (The cvar comes 0 by default).  Check that. Anyway i will current map to being loaded in menus. so it will fix that behavior.

Ps. is good idea change pug to be compatible with RE-HLDS?

**Comment by DionnyV** [comment]
Well, I guess I said it the other way around. I use ReHLDS + ReGameDLL without problems.

**Comment by SmileYzn** [comment]
Wait for next update, some cool things incoming :D

**Comment by SmileYzn** [comment]
Closed duo new version

**Pull request closed without merging**
